/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AccountRouteImport } from './routes/account'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as FriendClubRouteImport } from './routes/friend-club'
import { Route as GrowRouteImport } from './routes/grow'
import { Route as LoginRouteImport } from './routes/login'
import { Route as TreegalleryRouteImport } from './routes/treegallery'
import { Route as GrowIndexRouteImport } from './routes/grow.index'
import { Route as GrowDailytaskRouteImport } from './routes/grow.dailytask'
import { Route as GrowFlashcardRouteImport } from './routes/grow.flashcard'
import { Route as GrowPinoteRouteImport } from './routes/grow.pinote'
import { Route as GrowStudyRouteImport } from './routes/grow.study'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AccountRoute = AccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const FriendClubRoute = FriendClubRouteImport.update({
  id: '/friend-club',
  path: '/friend-club',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowRoute = GrowRouteImport.update({
  id: '/grow',
  path: '/grow',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const TreegalleryRoute = TreegalleryRouteImport.update({
  id: '/treegallery',
  path: '/treegallery',
  getParentRoute: () => rootRouteImport,
} as any)
const GrowIndexRoute = GrowIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => GrowRoute,
} as any)
const GrowDailytaskRoute = GrowDailytaskRouteImport.update({
  id: '/dailytask',
  path: '/dailytask',
  getParentRoute: () => GrowRoute,
} as any)
const GrowFlashcardRoute = GrowFlashcardRouteImport.update({
  id: '/flashcard',
  path: '/flashcard',
  getParentRoute: () => GrowRoute,
} as any)
const GrowPinoteRoute = GrowPinoteRouteImport.update({
  id: '/pinote',
  path: '/pinote',
  getParentRoute: () => GrowRoute,
} as any)
const GrowStudyRoute = GrowStudyRouteImport.update({
  id: '/study',
  path: '/study',
  getParentRoute: () => GrowRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/friend-club': typeof FriendClubRoute
  '/grow': typeof GrowRouteWithChildren
  '/login': typeof LoginRoute
  '/treegallery': typeof TreegalleryRoute
  '/grow/dailytask': typeof GrowDailytaskRoute
  '/grow/flashcard': typeof GrowFlashcardRoute
  '/grow/pinote': typeof GrowPinoteRoute
  '/grow/study': typeof GrowStudyRoute
  '/grow/': typeof GrowIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/friend-club': typeof FriendClubRoute
  '/login': typeof LoginRoute
  '/treegallery': typeof TreegalleryRoute
  '/grow/dailytask': typeof GrowDailytaskRoute
  '/grow/flashcard': typeof GrowFlashcardRoute
  '/grow/pinote': typeof GrowPinoteRoute
  '/grow/study': typeof GrowStudyRoute
  '/grow': typeof GrowIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/account': typeof AccountRoute
  '/admin': typeof AdminRoute
  '/friend-club': typeof FriendClubRoute
  '/grow': typeof GrowRouteWithChildren
  '/login': typeof LoginRoute
  '/treegallery': typeof TreegalleryRoute
  '/grow/dailytask': typeof GrowDailytaskRoute
  '/grow/flashcard': typeof GrowFlashcardRoute
  '/grow/pinote': typeof GrowPinoteRoute
  '/grow/study': typeof GrowStudyRoute
  '/grow/': typeof GrowIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/account'
    | '/admin'
    | '/friend-club'
    | '/grow'
    | '/login'
    | '/treegallery'
    | '/grow/dailytask'
    | '/grow/flashcard'
    | '/grow/pinote'
    | '/grow/study'
    | '/grow/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/account'
    | '/admin'
    | '/friend-club'
    | '/login'
    | '/treegallery'
    | '/grow/dailytask'
    | '/grow/flashcard'
    | '/grow/pinote'
    | '/grow/study'
    | '/grow'
  id:
    | '__root__'
    | '/'
    | '/account'
    | '/admin'
    | '/friend-club'
    | '/grow'
    | '/login'
    | '/treegallery'
    | '/grow/dailytask'
    | '/grow/flashcard'
    | '/grow/pinote'
    | '/grow/study'
    | '/grow/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AccountRoute: typeof AccountRoute
  AdminRoute: typeof AdminRoute
  FriendClubRoute: typeof FriendClubRoute
  GrowRoute: typeof GrowRouteWithChildren
  LoginRoute: typeof LoginRoute
  TreegalleryRoute: typeof TreegalleryRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/account': {
      id: '/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AccountRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/friend-club': {
      id: '/friend-club'
      path: '/friend-club'
      fullPath: '/friend-club'
      preLoaderRoute: typeof FriendClubRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow': {
      id: '/grow'
      path: '/grow'
      fullPath: '/grow'
      preLoaderRoute: typeof GrowRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/treegallery': {
      id: '/treegallery'
      path: '/treegallery'
      fullPath: '/treegallery'
      preLoaderRoute: typeof TreegalleryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/grow/': {
      id: '/grow/'
      path: '/'
      fullPath: '/grow/'
      preLoaderRoute: typeof GrowIndexRouteImport
      parentRoute: typeof GrowRoute
    }
    '/grow/dailytask': {
      id: '/grow/dailytask'
      path: '/dailytask'
      fullPath: '/grow/dailytask'
      preLoaderRoute: typeof GrowDailytaskRouteImport
      parentRoute: typeof GrowRoute
    }
    '/grow/flashcard': {
      id: '/grow/flashcard'
      path: '/flashcard'
      fullPath: '/grow/flashcard'
      preLoaderRoute: typeof GrowFlashcardRouteImport
      parentRoute: typeof GrowRoute
    }
    '/grow/pinote': {
      id: '/grow/pinote'
      path: '/pinote'
      fullPath: '/grow/pinote'
      preLoaderRoute: typeof GrowPinoteRouteImport
      parentRoute: typeof GrowRoute
    }
    '/grow/study': {
      id: '/grow/study'
      path: '/study'
      fullPath: '/grow/study'
      preLoaderRoute: typeof GrowStudyRouteImport
      parentRoute: typeof GrowRoute
    }
  }
}

interface GrowRouteChildren {
  GrowDailytaskRoute: typeof GrowDailytaskRoute
  GrowFlashcardRoute: typeof GrowFlashcardRoute
  GrowPinoteRoute: typeof GrowPinoteRoute
  GrowStudyRoute: typeof GrowStudyRoute
  GrowIndexRoute: typeof GrowIndexRoute
}

const GrowRouteChildren: GrowRouteChildren = {
  GrowDailytaskRoute: GrowDailytaskRoute,
  GrowFlashcardRoute: GrowFlashcardRoute,
  GrowPinoteRoute: GrowPinoteRoute,
  GrowStudyRoute: GrowStudyRoute,
  GrowIndexRoute: GrowIndexRoute,
}

const GrowRouteWithChildren = GrowRoute._addFileChildren(GrowRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AccountRoute: AccountRoute,
  AdminRoute: AdminRoute,
  FriendClubRoute: FriendClubRoute,
  GrowRoute: GrowRouteWithChildren,
  LoginRoute: LoginRoute,
  TreegalleryRoute: TreegalleryRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
